# Generated by Django 4.0.5 on 2022-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderc',
            name='weight',
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(default=12356423),
        ),
    ]
