# Generated by Django 4.0.5 on 2022-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cake_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='prise_sum',
        ),
        migrations.AlterField(
            model_name='orderc',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PREPAYMENT', 'Prepayment'), ('InPROGRESS', 'In Progress'), ('DONE', 'Done'), ('CakeHandedOver', 'Cake handed over'), ('DECLINED', 'Declined')], default='New', max_length=18),
        ),
    ]
