# Generated by Django 4.0.5 on 2022-06-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_orderc_prise_sum_alter_orderc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderc',
            name='prise_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
