# Generated by Django 4.0.5 on 2022-06-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderc_prise_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='confectioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.confectioner'),
        ),
    ]
