# Generated by Django 4.0.5 on 2022-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orderc_confectioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='prise_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
