# Generated by Django 4.0.5 on 2022-06-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orderc_prise_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='customer',
            field=models.ForeignKey(default='Vinohradov', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
