# Generated by Django 4.0.5 on 2022-06-17 20:57

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orderc_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='time_date_order',
            field=models.DateTimeField(validators=[shop.models.validation_date_time]),
        ),
    ]
