# Generated by Django 4.0.5 on 2022-06-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_orderc_time_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PREPAYMENT', 'Prepayment'), ('InPROGRESS', 'In Progress'), ('DONE', 'Done'), ('PAID', 'Paid'), ('CakeHandedOver', 'Cake handed over'), ('DECLINED', 'Declined')], default='New', max_length=18),
        ),
    ]
